language: php
php:
- 5.6
- hhvm

before_script: composer install
script:
- phpunit --bootstrap bootstrap.php --coverage-clover=coverage.clover --whitelist Tile Test
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover