language: php
php:
- 5.6
- hhvm

before_script: composer install
script:
- phpunit --configuration phpunit.xml --coverage-clover=coverage.clover
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover